version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "5000:5000"
    depends_on:
      - postgres-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  product-service:
    build: ./product-service
    ports:
      - "3000:3000"
    depends_on:
      - mongo-db
    environment:
      MONGO_URI: mongodb://mongo-db:27017/product_db

  mongo-db:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db

  order-service:
    build: ./order-service
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      MYSQL_DB: order_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: order_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  postgres_data:
  mongo_data:
  mysql_data:
